name: Build release binary

on:
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      env:
        APP: aur-check-updates
        VERSION: ${{ github.event.release.tag_name }}
        CARCH: x86_64
        RUSTUP_TOOLCHAIN: stable
        CARGO_TERM_COLOR: always
        UPLOAD_URL: ${{ github.event.release.upload_url }}

    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        run: |
          DEPS=('rust' 'mold')
          pacman -Syu --needed --noconfirm --color always "${DEPS[@]}"
          mkdir ".cargo"
          cp -pv ".github/workflows/config.toml" -t ".cargo"
          cargo fetch -v --locked --target "${CARCH}-unknown-linux-gnu"

      - name: Run tests
        run: cargo test -v --frozen

      - name: Build
        run: cargo build -v --frozen --release

      - name: Upload archive
        run: |
          cd "target/release"
          ARCHIVE="${APP}-${VERSION}-${CARCH}.tar.xz"
          sha256sum "${APP}" > "sha256sums.txt"
          tar -cvJf "${ARCHIVE}" "${APP}" "sha256sums.txt"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/x-tar" \
            --fail-with-body --connect-timeout 10 --retry 3 \
            --data-binary "@${ARCHIVE}" \
            "${UPLOAD_URL%'{'*}?name=${ARCHIVE}"
