[registries.crates-io]
protocol = "sparse"

[profile.release]
opt-level = 2
strip = true
lto = true
codegen-units = 1

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "target-cpu=generic",
    "-C", "link-arg=-fuse-ld=mold",
]
